AllCops:
  Exclude:
    - Rakefile
    - Berksfile
    - Vagrantfile
    - Thorfile
    - Gemfile
AlignParameters:
  Enabled: true
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 30
BracesAroundHashParameters:
  Enabled: true
CyclomaticComplexity:
  Enabled: false
GuardClause:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 14
